# Generated by Django 4.0.6 on 2022-08-19 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200)),
                ('celular', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fechaNac', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
