# Generated by Django 4.0.6 on 2022-08-19 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amigachos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.DateTimeField(),
        ),
    ]
