# Generated by Django 4.0.6 on 2022-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigachos', '0004_alter_persona_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
