# Generated by Django 4.0.6 on 2022-08-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigachos', '0005_alter_persona_fechanac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fechaNac',
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
